BLOCK_SIZE_IN_SECONDS = 0.4
BRIGHTNESS_MAX = 255
LEVEL_CHAR = "/"
DATA_HALT = "HALT"

# these are all files
DATA_NIGHT_VISION_LEVEL = "DATA_NIGHT_VISION_LEVEL"
DATA_LOUDNESS = "DATA_LOUDNESS"
DATA_LOUDNESS_BASE = "DATA_LOUDNESS_BASE"
DATA_LOUDNESS_SENSITIVITY = "DATA_LOUDNESS_SENSITIVITY"
DATA_ATMOSPHERE = "DATA_ATMOSPHERE"
DATA_ATMOSPHERE_OUTSIDE = "DATA_ATMOSPHERE_OUTSIDE"

DATA_ITEMS = [
    DATA_NIGHT_VISION_LEVEL,
    DATA_LOUDNESS,
    DATA_LOUDNESS_BASE,
    DATA_LOUDNESS_SENSITIVITY,
    DATA_ATMOSPHERE,
    DATA_ATMOSPHERE_OUTSIDE,
]
