BLOCK_SIZE_IN_SECONDS = 0.4
BRIGHTNESS_MAX = 255
LEVEL_CHAR = "/"
FILE_HALT = "HALT"

FILE_NIGHT_VISION = "NIGHT_VISION"
FILE_LOUDNESS = "LOUDNESS"
FILE_LOUDNESS_BASE = "LOUDNESS_BASE"
FILE_LOUDNESS_SENSITIVITY = "LOUDNESS_SENSITIVITY"
FILE_ATMOSPHERE = "ATMOSPHERE"
FILE_ATMOSPHERE_OUTSIDE = "ATMOSPHERE_OUTSIDE"

DATA_ITEMS = [
    FILE_NIGHT_VISION,
    FILE_LOUDNESS,
    FILE_LOUDNESS_BASE,
    FILE_LOUDNESS_SENSITIVITY,
    FILE_ATMOSPHERE,
    FILE_ATMOSPHERE_OUTSIDE,
]
